### ISSUE TITLE
Provide a binary

### ISSUE THREAD

**Issue by trycatcher** [souvikhaldar/huntsman#1]
Provide a binary so that this can be integrated with popular OS package archives.

**Comment by souvikhaldar** [comment]
> Provide a binary so that this can be integrated with popular OS package archives.

 I’ve added a script to cross compile go program for any platform, or multiple https://github.com/souvikhaldar/scripts/blob/master/goinstaller.py 
Now there are binaries available for Linux, Mac and Windows in the `download` directory.
